General improvements to HTTPS API (Second Edition)
sindresorhus/got pull request #1435
Opened 2020-09-03 10:38 UTC by Giotino

Following the previous "General improvements to HTTPS API" (#1255) this PR is going to add the remaining HTTPS options described in #1306 (or, at least, most of them).

This PR is still WIP.

#### Checklist

- [x] I have read the documentation.
- [ ] I have included a pull request description of my changes.
- [x] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates in both the README and the types.

(Partially) Fixes #1306

Fixes #1299

2021-01-13 07:35 UTC, sindresorhus requested changes

2021-01-13 07:35 UTC, sindresorhus commented on source/core/index.ts
> +	ciphers?: SecureContextOptions['ciphers'];
Can we make this support an array of ciphers instead of string with `:`?

2021-01-13 07:35 UTC, sindresorhus commented on test/https.ts
> +const ciphers = tls.getCiphers().map(cipher => cipher.toUpperCase());
Would be more readable if you used destructuring here.

2021-01-13 07:35 UTC, sindresorhus commented
Can you fix the merge conflicts?

2021-04-11 20:17 UTC, szmarczak requested changes
I just noticed hat I had this review pending for months. OMG.

2021-04-11 20:19 UTC, szmarczak commented
@Giotino Can you rebase this PR please? #1667 has been merged, I'm more than happy to answer all your questions if you encounter anything :)

2021-04-12 16:15 UTC, Giotino commented
> In order to be safe and not lose everything feel free to create a new PR and close this one. I think it will be easier to start from `master` again.

Yes, I think it's better to close this PR and open a new one, but recently I haven't been able to work on this repo.

2021-04-12 17:46 UTC, szmarczak commented
> recently I haven't been able to work on this repo

No worries!

2021-04-27 17:11 UTC, closed without merging